### ISSUE TITLE
Assertion error when building effdet model

### ISSUE THREAD

**Issue by mhmdsab** [rwightman/efficientdet-pytorch#170]
this error is  thrown when i try to load effdet b5:

Traceback (most recent call last):

  File "<ipython-input-9-2f5e4698315b>", line 1, in <module>
    DetBenchTrain(net, config)

  File "C:\Users\MSabry\anaconda3\lib\site-packages\effdet\bench.py", line 103, in __init__
    self.anchors = Anchors.from_config(model.config)

  File "C:\Users\MSabry\anaconda3\lib\site-packages\effdet\anchors.py", line 239, in from_config
    config.anchor_scale, config.image_size)

  File "C:\Users\MSabry\anaconda3\lib\site-packages\effdet\anchors.py", line 225, in __init__
    assert isinstance(image_size, Sequence) and len(image_size) == 2

AssertionError

Code i ran:

def get_net():
    config = get_efficientdet_config('tf_efficientdet_d5')
    config.num_classes = 1
    config.image_size = 512
    net = EfficientDet(config, pretrained_backbone=True)
    net.class_net = HeadNet(config, num_outputs=config.num_classes)
    return DetBenchTrain(net, config)

net = get_net()

**Comment by mhmdsab** [comment]
Solved, image size should be list [512, 512] instead of 512
