### ISSUE TITLE
Error during inference using pretrained TF weights for D5

### ISSUE THREAD

**Issue by khushigupta** [rwightman/efficientdet-pytorch#41]
I tried running COCO eval using TF ported weights for D5 as a sanity check and got an error. 
I don't get this error while running the same check on D0, D1 or D2. Don't know if there is a problem with the tensorflow weights or I'm supposed to call `.contiguous()` somewhere

This was my command: 
`python validate.py /mscoco --model tf_efficientdet_d5 --checkpoint tf_efficientdet_d5-ef44aea8.pth`

I get the following error:
```
Traceback (most recent call last):
  File "validate.py", line 188, in <module>
    main()
  File "validate.py", line 184, in main
    validate(args)
  File "validate.py", line 139, in validate
    output = bench(input, target['img_scale'], target['img_size'])
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kgupta/code/sixth_sense/efficientdet-pytorch/effdet/bench.py", line 73, in forward
    class_out, box_out = self.model(x)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kgupta/code/sixth_sense/efficientdet-pytorch/effdet/efficientdet.py", line 467, in forward
    x = self.backbone(x.contiguous())
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/timm/models/efficientnet.py", line 478, in forward
    x = self.conv_stem(x)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/timm/models/layers/conv2d_same.py", line 30, in forward
    return conv2d_same(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/timm/models/layers/conv2d_same.py", line 17, in conv2d_same
    return F.conv2d(x, weight, bias, stride, (0, 0), dilation, groups)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

**Comment by rwightman** [comment]
pretty sure that's triggered by running out of GPU memory (the error can be obfuscated), maybe a non-contiguous tensor caused by being almost OOM, either way, decreasing the batch size will likely fix it, the D5 requires a batch quite a bit smaller than the D0/1/2. You can see my batch size calcs in sotabench to have it running with comfortable margin on their V100 https://github.com/rwightman/efficientdet-pytorch/blob/master/sotabench.py
