### ISSUE TITLE
Validation failing with the error : Integer division of tensors using div or / is no longer supported.

### ISSUE THREAD

**Issue by Sriharsha-hatwar** [rwightman/efficientdet-pytorch#68]
Hello currently I am using pytorch 1.6
This is the error I am getting : 
```
Traceback (most recent call last):
  File "runner.py", line 181, in <module>
    main(0)
  File "runner.py", line 165, in main
    validation_score = validate(valid_dataset, valid_dataloader, model, device)
  File "runner.py", line 102, in validate
    output = model(images, target_res)
  File "/home/sriharsha/miniconda3/envs/machine_learning/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sriharsha/Desktop/kaggle/Global-Wheat-Detection/src/models.py", line 24, in forward
    return self.detBenchTrain(images, target)
  File "/home/sriharsha/miniconda3/envs/machine_learning/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sriharsha/miniconda3/envs/machine_learning/lib/python3.7/site-packages/effdet/bench.py", line 99, in forward
    class_out, box_out, indices, classes = _post_process(self.config, class_out, box_out)
  File "/home/sriharsha/miniconda3/envs/machine_learning/lib/python3.7/site-packages/effdet/bench.py", line 37, in _post_process
    indices_all = cls_topk_indices_all / config.num_classes
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
```
If I am right this should be a tiny fix? Let me know if there is any mistake from my end.

**Comment by rwightman** [comment]
already fixed
